- menu_name: "Services | Сервіси"

- name: "Contact | Контакти"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "Sitemap"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
