name: Automake GitHub site on Pelican

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: develop
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Make static pages
      run: pelican content -o gh-output -s publishconf.py
    - name: Create gh-pages branch
      run: ghp-import gh-output
    - name: Push to master
      run: git push --force https://${{ secrets.ACESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git gh-pages:master